### ISSUE TITLE
Image ratio should be limited

### ISSUE THREAD

**Issue by Liaune** [kingdido999/atogatari#1]
上传了两张测试图片，发现图片的比例没有一个限制，尤其是图片的高度，超高尺寸图片彻底把版面破坏了（抱歉了，请删掉那两张测试图片吧~）
我觉得可以把展示比例固定为16:9
至于上传的比例，没有好的解决办法，因为有些动画圆盘有奇葩的分辨率，不能用简单的比例来限制

**Comment by kingdido999** [comment]
嗯，感谢测试！
