### ISSUE TITLE
Last picture repeat when delete in /tag/ page

### ISSUE THREAD

**Issue by Liaune** [kingdido999/atogatari#10]
The last picture will repeat if I delete picture in /tag/ page

**Comment by kingdido999** [comment]
What do you mean by repeat?

**Comment by Liaune** [comment]
If I delete a picture, the last picture of the page will repeat, actually they are the same picture, but shown in 2, something like delay.

**Comment by Liaune** [comment]
Now the problem has gone because of pagination added in all pages
