### ISSUE TITLE
Add classification for "no tag" pictures

### ISSUE THREAD

**Issue by Liaune** [kingdido999/atogatari#5]
If someone forget to add tag when uploading，it's not easy to find out those "no tag" pictures, add a classification for "no tag" pictures will help a lot.

**Comment by kingdido999** [comment]
Now we can sort pictures by the number of tags in ascending order, which means "no tag" pictures will come first. A small advantage over filtering by "zero tag" only is that it helps you discover screenshots that have limited number of tags.

I will put the number of tags on the screenshot card later.
