### ISSUE TITLE
Delete tag

### ISSUE THREAD

**Issue by Liaune** [kingdido999/atogatari#8]
Add some wrong tags by mistake, please help to deal with it.

https://atogatari.com/screenshot/58feab8fb2d83a26e170d207

**Comment by kingdido999** [comment]
Upgraded you to Admin, see if you can delete that tag by yourself :)

**Comment by Liaune** [comment]
Thanks. delete successful.
But the page will empty if delete a tag in tag/ page.

**Comment by kingdido999** [comment]
I made a fix so that one tag can only be removed within its screenshot page (/screenshot/:id). Notice that deleting a tag here means remove a tag from a screenshot, we're not allowed to delete one tag entirely at this moment.
